# Generated by Django 5.1.6 on 2025-02-19 00:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('displayName', models.CharField(max_length=256)),
                ('host', models.URLField(blank=True, default=None, null=True)),
                ('github', models.URLField(blank=True, default=None, null=True)),
                ('profileImageURL', models.URLField(blank=True, default=None, null=True)),
                ('page', models.URLField(blank=True, default=None, null=True)),
                ('is_local', models.BooleanField(default=True)),
                ('username', models.CharField(max_length=128, unique=True)),
                ('state', models.CharField(choices=[('PENDING', 'PENDING'), ('ACTIVE', 'ACTIVE'), ('DELETED', 'DELETED')], default='PENDING', max_length=7)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
