# Generated by Django 5.1.6 on 2025-02-20 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='id_url',
            field=models.URLField(default='http://localhost:8000'),
            preserve_default=False,
        ),
    ]
