# Generated by Django 5.1.6 on 2025-03-18 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_author_id_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='profileImageURL',
            new_name='profileImage',
        ),
    ]
