# Generated by Django 5.1.6 on 2025-03-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0003_rename_profileimageurl_author_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id_url',
            field=models.URLField(unique=True),
        ),
    ]
