# Generated by Django 5.1.6 on 2025-03-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0004_alter_author_id_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='is_node',
            field=models.BooleanField(default=False),
        ),
    ]
