# Generated by Django 5.1.6 on 2025-03-29 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0005_author_is_node'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='github',
        ),
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.URLField(default=None),
        ),
    ]
