# Generated by Django 5.1.6 on 2025-03-30 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0007_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='host',
            name='host',
            field=models.URLField(unique=True),
        ),
    ]
