# Generated by Django 5.1.6 on 2025-02-21 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='isPending',
            field=models.BooleanField(default=True),
        ),
    ]
