# Generated by Django 5.1.6 on 2025-04-02 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reel',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('FRIENDS', 'Friends Only'), ('UNLISTED', 'Unlisted')], default='PUBLIC', max_length=10),
        ),
    ]
