# Generated by Django 5.1.6 on 2025-02-22 06:29

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0002_author_id_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='like', max_length=100)),
                ('published', models.DateTimeField(default=datetime.datetime.now)),
                ('id_url', models.URLField(unique=True)),
                ('object', models.URLField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authors.author')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='post', max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('id_url', models.URLField(unique=True)),
                ('page', models.URLField()),
                ('description', models.CharField(max_length=200)),
                ('contentType', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'PUBLIC'), ('FRIENDS', 'FRIENDS'), ('UNLISTED', 'UNLISTED'), ('DELETED', 'DELETED')], default='PUBLIC', max_length=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authors.author')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='comment', max_length=100)),
                ('comment', models.TextField()),
                ('contentType', models.CharField(max_length=100)),
                ('published', models.DateTimeField(default=datetime.datetime.now)),
                ('id_url', models.URLField(unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authors.author')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
            ],
        ),
    ]
