# Generated by Django 5.1.6 on 2025-02-17 23:56

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(default='post', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='visibility',
            field=models.CharField(default='public', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='id_url',
            field=models.URLField(unique=True),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='comment', max_length=100)),
                ('comment', models.TextField()),
                ('contentType', models.CharField(max_length=100)),
                ('published', models.DateTimeField(default=datetime.datetime.now)),
                ('id_url', models.URLField(unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authors.author')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='like', max_length=100)),
                ('published', models.DateTimeField(default=datetime.datetime.now)),
                ('id_url', models.URLField(unique=True)),
                ('object', models.URLField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authors.author')),
            ],
        ),
    ]
