# Generated by Django 5.1.6 on 2025-02-22 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='type',
        ),
        migrations.RemoveField(
            model_name='like',
            name='type',
        ),
        migrations.AddField(
            model_name='comment',
            name='page',
            field=models.URLField(default='http://localhost:8000'),
            preserve_default=False,
        ),
    ]
