# Generated by Django 5.1.6 on 2025-02-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_comment_type_remove_like_type_comment_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='page',
            field=models.URLField(blank=True, null=True),
        ),
    ]
