# Generated by Django 5.1.6 on 2025-02-19 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_published_alter_post_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id_url',
            field=models.UUIDField(),
        ),
    ]
