# Generated by Django 5.1.6 on 2025-03-05 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_comment_published_alter_like_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='type',
        ),
    ]
