# Generated by Django 5.1.6 on 2025-03-09 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_author_id_url'),
        ('posts', '0004_alter_comment_published_alter_like_published'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('author', 'object'), name='unique_like'),
        ),
    ]
