# Generated by Django 5.1.6 on 2025-02-19 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_id_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id_url',
            field=models.URLField(unique=True),
        ),
    ]
