# Generated by Django 5.1.6 on 2025-03-09 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_like_unique_like'),
        ('posts', '0005_remove_post_type'),
    ]

    operations = [
    ]
